INCLUDEPATH += ./Extended/Networks/Parameters \
    ./Extended/Networks/Tools \
    ./Extended/Networks/Repositories \
    ./Extended/Networks/RDomainAdd \
    ./Extended/Networks/Estimators \
    ./Extended/Networks/Models/Buildings \
    ./Extended/Networks/Models/Power \
    ./Extended/Networks/Models/Water \
    ./Extended/Networks/Models/Transportation \
    ./Extended/Networks/Models/Fuel \
    ./Extended/Networks/Models/Orchestrating \
    ./Extended/Networks/Models/Businesses \


HEADERS += ./Extended/Networks/Models/Orchestrating/RNetworkModel.h \
    ./Extended/Networks/Models/Orchestrating/RNetworkManagerModel.h \
    ./Extended/Networks/Models/Orchestrating/RNetworkSamplingModel.h \
    ./Extended/Networks/Models/Buildings/RNeighborhoodModel.h \
    ./Extended/Networks/Models/Buildings/RResidentialMobilityNeighborhoodModel.h \
    ./Extended/Networks/Models/Buildings/RMainNeighborhoodModel.h \
    ./Extended/Networks/Models/Buildings/RWorkforceStudyNeighborhoodModel.h \
    ./Extended/Networks/Models/Buildings/RRecoveryStrategyStudyNeighborhoodModel.h \
    ./Extended/Networks/Models/Power/RPowerLineModel.h \
    ./Extended/Networks/Models/Power/RPowerDamModel.h \
    ./Extended/Networks/Models/Power/RPowerSubstationModel.h \
    ./Extended/Networks/Models/Water/RWaterPumpStationModel.h \
    ./Extended/Networks/Models/Water/RWaterPipelineModel.h \
    ./Extended/Networks/Models/Water/RWaterDamModel.h \
    ./Extended/Networks/Models/Water/RWaterReservoirModel.h \
    ./Extended/Networks/Models/Water/RWaterStorageTankModel.h \
    ./Extended/Networks/Models/Water/RWaterTreatmentFacilityModel.h \
    ./Extended/Networks/Models/Water/RWaterDemandZoneModel.h \
    ./Extended/Networks/Models/Transportation/RBridgeModel.h \
    ./Extended/Networks/Models/Transportation/RPortModel.h \
    ./Extended/Networks/Models/Transportation/RRailwayDispatchFacilityModel.h \
    ./Extended/Networks/Models/Transportation/RRailwayFuelFacilityModel.h \
    ./Extended/Networks/Models/Transportation/RRoadwayModel.h \
    ./Extended/Networks/Models/Transportation/RShippingChannelModel.h \
    ./Extended/Networks/Models/Fuel/RRefineryModel.h \
    ./Extended/Networks/Models/Fuel/RGenericFuelSourceModel.h \
    ./Extended/Networks/Models/Fuel/RFuelTankFarmModel.h \
    ./Extended/Networks/Models/Fuel/RFuelPipelineModel.h \
    ./Extended/Networks/Models/Fuel/RFuelSourceModel.h \
    ./Extended/Networks/Models/Fuel/RCommunityModel.h \
    ./Extended/Networks/Models/Businesses/RSingleFamilyContractorFirmModel.h \
    ./Extended/Networks/Models/Businesses/RMultiFamilyContractorFirmModel.h \
    ./Extended/Networks/Models/Businesses/RContractorNegotiationModel.h \
    ./Extended/Networks/Models/Businesses/REngineeringFirmModel.h \
    ./Extended/Networks/Models/Businesses/RInspectorModel.h \
    ./Extended/Networks/Models/Businesses/RPermitAssessorModel.h \
    ./Extended/Networks/Models/Businesses/RPrivateMoneyLenderModel.h \
    ./Extended/Networks/Models/Businesses/RPublicMoneyLenderModel.h \
    ./Extended/Networks/Models/Businesses/RGrantProviderModel.h \
    ./Extended/Networks/Models/Businesses/RInsuranceCompanyModel.h \
    ./Extended/Networks/Models/Businesses/RGenericMaterialsSupplierModel.h \
    ./Extended/Networks/Models/Businesses/RHardwareStoreModel.h \
    ./Extended/Networks/Models/Businesses/RConcretePlantModel.h \
    ./Extended/Networks/Estimators/RPopulationDisplacementEstimator.h \
    ./Extended/Networks/Estimators/RAHSPopulationDisplacementEstimator.h \
    ./Extended/Networks/Estimators/RHAZUSPopulationDisplacementEstimator.h \
    ./Extended/Networks/Estimators/RDisasterPreparednessEstimator.h \
    ./Extended/Networks/Estimators/RStatisticsCanadaPreparednessEstimator.h \
    ./Extended/Networks/Estimators/RAHSPreparednessEstimator.h \
    ./Extended/Networks/Estimators/RSutley2016MorbidityEstimator.h \
    ./Extended/Networks/Parameters/RContractorNegotiationRequest.h \
    ./Extended/Networks/Parameters/RMultiFamilyContractorRequest.h \
    ./Extended/Networks/Parameters/RPacket.h \
    ./Extended/Networks/Parameters/RPacketResponse.h \
    ./Extended/Networks/Parameters/RRequest.h \
    ./Extended/Networks/Parameters/RFinancingRequest.h \
    ./Extended/Networks/Parameters/REngineeringAssessmentRequest.h \
    ./Extended/Networks/Parameters/RPermitRequest.h \
    ./Extended/Networks/Parameters/RSingleFamilyContractorRequest.h \
    ./Extended/Networks/Repositories/RBuildingPortfolio.h \
    ./Extended/Networks/Repositories/RCensusBuildingPortfolio.h \
    ./Extended/Networks/Repositories/RSimCenterBuildingPortfolio.h \
    ./Extended/Networks/Repositories/RHAZUSBuildingPortfolio.h \
    ./Extended/Networks/Repositories/RSimplyAnalyticsBuildingPortfolio.h \
    ./Extended/Networks/Repositories/RHouseholdPortfolio.h \



SOURCES += ./Extended/Networks/Models/Orchestrating/RNetworkModel.cpp \
    ./Extended/Networks/Models/Orchestrating/RNetworkManagerModel.cpp \
    ./Extended/Networks/Models/Orchestrating/RNetworkSamplingModel.cpp \
    ./Extended/Networks/Models/Buildings/RNeighborhoodModel.cpp \
    ./Extended/Networks/Models/Buildings/RResidentialMobilityNeighborhoodModel.cpp \
    ./Extended/Networks/Models/Buildings/RMainNeighborhoodModel.cpp \
    ./Extended/Networks/Models/Buildings/RWorkforceStudyNeighborhoodModel.cpp \
    ./Extended/Networks/Models/Buildings/RRecoveryStrategyStudyNeighborhoodModel.cpp \
    ./Extended/Networks/Models/Power/RPowerLineModel.cpp \
    ./Extended/Networks/Models/Power/RPowerDamModel.cpp \
    ./Extended/Networks/Models/Power/RPowerSubstationModel.cpp \
    ./Extended/Networks/Models/Water/RWaterPumpStationModel.cpp \
    ./Extended/Networks/Models/Water/RWaterPipelineModel.cpp \
    ./Extended/Networks/Models/Water/RWaterDamModel.cpp \
    ./Extended/Networks/Models/Water/RWaterReservoirModel.cpp \
    ./Extended/Networks/Models/Water/RWaterStorageTankModel.cpp \
    ./Extended/Networks/Models/Water/RWaterTreatmentFacilityModel.cpp \
    ./Extended/Networks/Models/Water/RWaterDemandZoneModel.cpp \
    ./Extended/Networks/Models/Transportation/RBridgeModel.cpp \
    ./Extended/Networks/Models/Transportation/RPortModel.cpp \
    ./Extended/Networks/Models/Transportation/RPortModel.cpp \
    ./Extended/Networks/Models/Transportation/RRailwayDispatchFacilityModel.cpp \
    ./Extended/Networks/Models/Transportation/RRailwayFuelFacilityModel.cpp \
    ./Extended/Networks/Models/Transportation/RRoadwayModel.cpp \
    ./Extended/Networks/Models/Transportation/RShippingChannelModel.cpp \
    ./Extended/Networks/Models/Fuel/RRefineryModel.cpp \
    ./Extended/Networks/Models/Fuel/RGenericFuelSourceModel.cpp \
    ./Extended/Networks/Models/Fuel/RFuelTankFarmModel.cpp \
    ./Extended/Networks/Models/Fuel/RFuelPipelineModel.cpp \
    ./Extended/Networks/Models/Fuel/RFuelSourceModel.cpp \
    ./Extended/Networks/Models/Fuel/RCommunityModel.cpp \
    ./Extended/Networks/Models/Businesses/RSingleFamilyContractorFirmModel.cpp \
    ./Extended/Networks/Models/Businesses/RMultiFamilyContractorFirmModel.cpp \
    ./Extended/Networks/Models/Businesses/RContractorNegotiationModel.cpp \
    ./Extended/Networks/Models/Businesses/REngineeringFirmModel.cpp \
    ./Extended/Networks/Models/Businesses/RInspectorModel.cpp \
    ./Extended/Networks/Models/Businesses/RPermitAssessorModel.cpp \
    ./Extended/Networks/Models/Businesses/RPrivateMoneyLenderModel.cpp \
    ./Extended/Networks/Models/Businesses/RPublicMoneyLenderModel.cpp \
    ./Extended/Networks/Models/Businesses/RGrantProviderModel.cpp \
    ./Extended/Networks/Models/Businesses/RInsuranceCompanyModel.cpp \
    ./Extended/Networks/Models/Businesses/RGenericMaterialsSupplierModel.cpp \
    ./Extended/Networks/Models/Businesses/RHardwareStoreModel.cpp \
    ./Extended/Networks/Models/Businesses/RConcretePlantModel.cpp \
    ./Extended/Networks/Estimators/RPopulationDisplacementEstimator.cpp \
    ./Extended/Networks/Estimators/RAHSPopulationDisplacementEstimator.cpp \
    ./Extended/Networks/Estimators/RHAZUSPopulationDisplacementEstimator.cpp \
    ./Extended/Networks/Estimators/RDisasterPreparednessEstimator.cpp \
    ./Extended/Networks/Estimators/RStatisticsCanadaPreparednessEstimator.cpp \
    ./Extended/Networks/Estimators/RAHSPreparednessEstimator.cpp \
    ./Extended/Networks/Estimators/RSutley2016MorbidityEstimator.cpp \
    ./Extended/Networks/Parameters/RPacket.cpp \
    ./Extended/Networks/Parameters/RPacketResponse.cpp \
    ./Extended/Networks/Parameters/RRequest.cpp \
    ./Extended/Networks/Parameters/RFinancingRequest.cpp \
    ./Extended/Networks/Parameters/REngineeringAssessmentRequest.cpp \
    ./Extended/Networks/Parameters/RPermitRequest.cpp \
    ./Extended/Networks/Parameters/RSingleFamilyContractorRequest.cpp \
    ./Extended/Networks/Parameters/RMultiFamilyContractorRequest.cpp \
    ./Extended/Networks/Parameters/RContractorNegotiationRequest.cpp \
    ./Extended/Networks/Repositories/RBuildingPortfolio.cpp \
    ./Extended/Networks/Repositories/RCensusBuildingPortfolio.cpp \
    ./Extended/Networks/Repositories/RSimCenterBuildingPortfolio.cpp \
    ./Extended/Networks/Repositories/RHAZUSBuildingPortfolio.cpp \
    ./Extended/Networks/Repositories/RSimplyAnalyticsBuildingPortfolio.cpp \
    ./Extended/Networks/Repositories/RHouseholdPortfolio.cpp \


HEADERS += ./Extended/Networks/RDomainAdd/NetworkIncludes.h \
           ./Extended/Networks/RDomainAdd/NetworkMenu.h \
           ./Extended/Networks/RDomainAdd/CreateNetworkObjects.h \

